version: "3.8"

services:
  h2:
    image: oscarfonts/h2
    container_name: h2
    ports:
      - "1521:1521"
      - "81:81"
    volumes:
      - h2-data:/opt/h2-data
    environment:
      H2_OPTIONS: "-ifNotExists"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - patria-network

  java:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patria-test-api
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    depends_on:
      h2:
        condition: service_healthy
    networks:
      - patria-network

networks:
  patria-network:
    driver: bridge

volumes:
  h2-data:
